<#
The deployment plan for a greenfield Exchange Server SE deployment.

This is the one input the assessment cannot discover for itself. Domain controllers, domains and
the forest are discovered from Active Directory, and existing Exchange servers are discovered with
Get-ExchangeServer - none of those is ever supplied here. A member server that is going to become
an Exchange server is not an Exchange server yet, so Get-ExchangeServer cannot return it, and the
directory cannot say which server will host the file share witness or what the planned names
are. The operator supplies those, in this file.

Do not edit this file in place. It ships with the module, and the next update replaces it.
Write a fillable copy, fill it per client, and pass it to the run:

    New-ExchDeploymentConfig -Path .\Deployment.psd1
    .\scripts\Invoke-ExchAssess.ps1 -TenantHint <name> -ConfigPath .\Deployment.psd1

-ConfigPath is New-ExchRun's -ConfigPath: the file's keys are merged over Config/Thresholds.psd1,
so the Deployment section rides on the run's configuration alongside the thresholds. A run takes
one -ConfigPath, so a client that also has threshold overrides keeps both in the same file.

A filled copy holds client host names. Never commit one to source control, and never fill in this
template: it ships empty, and a test holds it empty.

No collector reads this section yet. It is the contract the greenfield deployment controls are to
be written against (PORT-PLAN P14). Today the preflight check reads it and warns, naming each key,
when any is missing or empty. A missing deployment config is expected for an assessment of an
existing organisation and never fails the run.

An empty string, an empty array, and an array holding only empty strings all count as not
supplied.
#>
@{
    # --------------------------------------------------------------------------------------
    # Greenfield deployment plan
    # Supplied by the operator. Nothing in this section can be discovered from the directory.
    # --------------------------------------------------------------------------------------
    Deployment = @{
        # Member servers that will become the Exchange servers, by fully qualified name. They
        # are not Exchange servers yet, so Get-ExchangeServer cannot return them.
        # Supplied: the deployment controls know which hosts to assess before Exchange is
        # installed on them.
        # Empty: preflight names TargetServers as missing, and every per-server deployment
        # check will report Unknown - the tool does not guess which member servers are meant.
        TargetServers  = @()

        # The server that will host the DAG's file share witness, by fully qualified name. It is
        # not one of TargetServers and not a domain controller.
        # Supplied: the witness host can be assessed alongside the target servers.
        # Empty: preflight names WitnessServer as missing, and the witness checks will report
        # Unknown.
        WitnessServer  = ''

        # The planned name of the database availability group.
        # Supplied: the planned name can be checked before the DAG is created.
        # Empty: preflight names DagName as missing, and the DAG name checks will report
        # Unknown.
        DagName        = ''

        # The internal namespace: the fully qualified names that clients inside the network will
        # use to reach Exchange.
        # Supplied: the planned namespace can be checked before it is published.
        # Empty: preflight names InternalNames as missing, and the namespace checks will report
        # Unknown.
        InternalNames  = @()

        # The volume that will hold the mailbox databases on each target server - a drive
        # letter or a mount point path.
        # Supplied: the database volume on each target server can be checked before databases
        # are placed on it.
        # Empty: preflight names DatabaseVolume as missing, and the database volume checks will
        # report Unknown.
        DatabaseVolume = ''

        # The volume that will hold the transaction logs on each target server - a drive letter
        # or a mount point path.
        # Supplied: the log volume on each target server can be checked before logs are placed
        # on it.
        # Empty: preflight names LogVolume as missing, and the log volume checks will report
        # Unknown.
        LogVolume      = ''
    }
}
